baseURL = 'http://saygo-png.github.io/'
languageCode = 'en-us'
title = "Saygo's liar"
theme = 'lugo'

[params]
 # "relatedtext" is the text that appears above the tag list at the bottom of pages.
 relatedtext = "Related"
 favicon = "/favicon.ico"
 description = "personal website of Saygo"
 
 #list items
 datesinlist = true
 authorsinlist = true

 #footer items
 nextprev = true
 taglist = true
 showrss = true

 extensions = [
  "laxHtmlBlocks", # laxer block handling
  "hardLineBreak", # newlines result in line breaks
 ]
